/**
 * GraphQL Schema Conformance Tests
 *
 * Every other test in this repo mocks the GraphQL client, so they verify that
 * we *call* the API but never that the API would accept what we send. That gap
 * let all 16 operations ship querying fields SuperOps does not define (see
 * CHANGELOG 1.2.6) — a `phone` field on Client, Relay-style `first`/`after`
 * pagination, subselections on JSON scalars.
 *
 * This suite closes it: every GraphQL document in src/domains is validated
 * against the real SuperOps schema (schema/superops.graphql, generated by
 * scripts/fetch-schema.mjs) with no network access required.
 */

import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative } from "node:path";
import { buildSchema, parse, validate, specifiedRules } from "graphql";

const here = dirname(fileURLToPath(import.meta.url));
const srcRoot = join(here, "..");
const schema = buildSchema(
  readFileSync(join(srcRoot, "..", "schema", "superops.graphql"), "utf8")
);

/** `const FOO_QUERY = ` … ` ` — the shape every operation in this repo uses. */
const TEMPLATE = /const\s+([A-Z0-9_]+)\s*=\s*`([\s\S]*?)`;/g;

interface Operation {
  file: string;
  name: string;
  body: string;
  interpolated: boolean;
}

/** Every non-test .ts file under src/, so no operation escapes validation. */
function sourceFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) return sourceFiles(full);
    if (!entry.name.endsWith(".ts") || entry.name.endsWith(".test.ts")) return [];
    return [full];
  });
}

function collectOperations(): Operation[] {
  const found: Operation[] = [];
  for (const path of sourceFiles(srcRoot)) {
    const source = readFileSync(path, "utf8");
    for (const [, name, body] of source.matchAll(TEMPLATE)) {
      if (!/\b(query|mutation)\s+\w/.test(body)) continue;
      found.push({
        file: relative(srcRoot, path),
        name,
        body,
        interpolated: body.includes("${"),
      });
    }
  }
  return found;
}

const operations = collectOperations();

describe("GraphQL schema conformance", () => {
  it("finds the GraphQL operations to validate", () => {
    // Guards against the regex silently matching nothing after a refactor,
    // which would make every assertion below vacuously pass.
    expect(operations.length).toBeGreaterThan(0);
  });

  it.each(operations)("$file :: $name is valid against the SuperOps schema", (op) => {
    // An interpolated document cannot be validated statically. Fail loudly
    // rather than skipping, so coverage can never regress unnoticed.
    expect(op.interpolated, `${op.name} interpolates a value and cannot be validated`).toBe(
      false
    );

    const errors = validate(schema, parse(op.body), specifiedRules);
    expect(errors.map((e) => e.message)).toEqual([]);
  });
});
