/**
 * GraphQL Schema Conformance Tests
 *
 * Every other test in this repo mocks the GraphQL client, so they verify that
 * we *call* the API but never that the API would accept what we send. That gap
 * let all 16 operations ship querying fields SuperOps does not define (see
 * CHANGELOG 1.2.6) — a `phone` field on Client, Relay-style `first`/`after`
 * pagination, subselections on JSON scalars.
 *
 * This suite closes it: every GraphQL document in src/domains is validated
 * against the real SuperOps schema (schema/superops.graphql, generated by
 * scripts/fetch-schema.mjs) with no network access required.
 */

import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative } from "node:path";
import {
  buildSchema,
  parse,
  validate,
  specifiedRules,
  visit,
  visitWithTypeInfo,
  TypeInfo,
  getNamedType,
  isObjectType,
  Kind,
} from "graphql";

const here = dirname(fileURLToPath(import.meta.url));
const srcRoot = join(here, "..");
const schema = buildSchema(
  readFileSync(join(srcRoot, "..", "schema", "superops.graphql"), "utf8")
);

/**
 * Every backtick template literal in the file, with the name of the `const` it
 * is assigned to when there is one.
 *
 * Deliberately NOT anchored to `const UPPER_SNAKE = ...`: an operation declared
 * with a lowercase name, built inside a function, or passed inline to
 * `client.query()` would then never be collected, and the suite would still go
 * green while that query was unvalidated — the exact blind spot that let the
 * original schema mismatch ship.
 */
const TEMPLATE = /(?:const\s+(\w+)\s*=\s*)?`([\s\S]*?)`/g;

/** A document must OPEN with `query Name`/`mutation Name` to be one of ours. */
const IS_OPERATION = /^\s*(?:query|mutation)\s+\w/;

interface Operation {
  file: string;
  name: string;
  body: string;
  interpolated: boolean;
}

/** Every non-test .ts file under src/, so no operation escapes validation. */
function sourceFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) return sourceFiles(full);
    if (!entry.name.endsWith(".ts") || entry.name.endsWith(".test.ts")) return [];
    return [full];
  });
}

function collectOperations(): Operation[] {
  const found: Operation[] = [];
  for (const path of sourceFiles(srcRoot)) {
    const source = readFileSync(path, "utf8");
    for (const [, constName, body] of source.matchAll(TEMPLATE)) {
      if (!IS_OPERATION.test(body)) continue;
      found.push({
        file: relative(srcRoot, path),
        // Fall back to the operation name for an anonymous/inline document.
        name: constName ?? body.trim().split(/[\s({]/)[1] ?? "<inline>",
        body,
        interpolated: body.includes("${"),
      });
    }
  }
  return found;
}

const operations = collectOperations();

describe("GraphQL schema conformance", () => {
  it("finds the GraphQL operations to validate", () => {
    // Guards against the regex silently matching nothing after a refactor,
    // which would make every assertion below vacuously pass.
    expect(operations.length).toBeGreaterThan(0);
  });

  it("collects an operation from every file that talks to the API", () => {
    // A file can call query()/mutate() only with a document, so one that sends
    // requests but contributes no validated operation means collection missed
    // it — the suite would stay green over an unchecked query.
    //
    // Two files legitimately send no static document:
    //   client.ts   — defines query()/mutate() themselves; it is the transport.
    //   custom.ts   — superops_custom_query/_mutation forward a caller-supplied
    //                 string, which cannot be known until runtime.
    const NO_STATIC_DOCUMENT = new Set(["client.ts", "domains/custom.ts"]);

    const covered = new Set(operations.map((op) => op.file));
    const senders = sourceFiles(srcRoot)
      .filter((path) => /\.(?:query|mutate)[<(]/.test(readFileSync(path, "utf8")))
      .map((path) => relative(srcRoot, path))
      .filter((file) => !NO_STATIC_DOCUMENT.has(file));

    expect(senders.length).toBeGreaterThan(0);
    expect(senders.filter((file) => !covered.has(file))).toEqual([]);
  });

  it.each(operations)("$file :: $name is valid against the SuperOps schema", (op) => {
    // An interpolated document cannot be validated statically. Fail loudly
    // rather than skipping, so coverage can never regress unnoticed.
    expect(op.interpolated, `${op.name} interpolates a value and cannot be validated`).toBe(
      false
    );

    const errors = validate(schema, parse(op.body), specifiedRules);
    expect(errors.map((e) => e.message)).toEqual([]);
  });

  /**
   * SuperOps list wrappers misbehave when the row collection is left out, and
   * neither failure is a GraphQL error — so validation alone cannot catch them:
   *
   *   getClientList { listInfo { totalCount } }   -> HTTP 500
   *   getTicketList { tickets { subject } … }     -> [] with a correct
   *                                                  filter-aware totalCount,
   *                                                  unless ticketId is selected
   *
   * Both were found by hand against a live tenant and were being defended by
   * "do not simplify this" comments. This asserts the general rule instead: any
   * selection on a `listInfo`-bearing wrapper must also select its row
   * collection, with at least one field.
   */
  it.each(operations)("$file :: $name selects the rows, not just listInfo", (op) => {
    const typeInfo = new TypeInfo(schema);
    const offenders: string[] = [];

    visit(
      parse(op.body),
      visitWithTypeInfo(typeInfo, {
        [Kind.SELECTION_SET](node) {
          const parent = getNamedType(typeInfo.getParentType() ?? undefined);
          if (!isObjectType(parent) || !parent.getFields().listInfo) return;

          const selected = new Set(
            node.selections
              .filter((s) => s.kind === Kind.FIELD)
              .map((s) => (s as { name: { value: string } }).name.value)
          );
          if (!selected.has("listInfo")) return;

          const rows = Object.keys(parent.getFields()).filter((f) => f !== "listInfo");
          if (!rows.some((f) => selected.has(f))) {
            offenders.push(`${parent.name} selects listInfo but none of: ${rows.join(", ")}`);
          }
        },
      })
    );

    expect(offenders).toEqual([]);
  });
});
