/**
 * SuperOps MCP Server Types
 *
 * Type definitions for the SuperOps.ai GraphQL API integration.
 *
 * These mirror schema/superops.graphql (generated by scripts/fetch-schema.mjs
 * from https://developer.superops.com/msp). Several SuperOps fields are typed
 * as the `JSON` scalar rather than as object types — `client`, `requester`,
 * `technician`, `customFields` and friends. GraphQL forbids a subselection on a
 * scalar, so those arrive as whole opaque values and are modelled here as
 * `unknown`/`Json`. Do not "improve" them into nested selections: the API
 * rejects the query outright.
 */

export interface SuperOpsCredentials {
  apiToken: string;
  subdomain: string;
  region?: "us" | "eu";
}

export interface GraphQLResponse<T = unknown> {
  data?: T;
  errors?: GraphQLError[];
}

export interface GraphQLError {
  message: string;
  locations?: { line: number; column: number }[];
  path?: string[];
  extensions?: {
    code?: string;
    retryAfter?: number;
    field?: string;
  };
}

/** A value SuperOps returns through the `JSON` scalar. */
export type Json = unknown;

/**
 * Pagination metadata. SuperOps uses page/pageSize offsets — not Relay cursors,
 * so there is no `hasNextPage`/`endCursor` here.
 *
 * `hasMore` is tri-state on the wire: `true` when a further page exists and
 * `null` — never `false` — when it does not. Verified against a live tenant.
 * Loop on `hasMore === true`, never on `hasMore === false`, or you never
 * terminate. `totalCount` is reliable and is the safer basis for paging.
 */
export interface ListInfo {
  page?: number;
  pageSize?: number;
  totalCount?: number;
  hasMore?: boolean | null;
  sort?: SortInput[];
  condition?: Json;
}

/**
 * A filter condition — either a single clause, or a compound of clauses joined
 * by `joinOperator`. The published docs describe only the flat form, but live
 * introspection and live queries confirm the recursive one:
 *
 *   { joinOperator: "OR", operands: [
 *       { attribute: "name",         operator: "contains", value: "acme" },
 *       { attribute: "emailDomains", operator: "contains", value: "acme" },
 *   ]}
 *
 * `joinOperator` MUST be uppercase. Anything the API does not recognise —
 * lowercase "and", or outright junk — is silently ignored and the operands are
 * joined with OR instead, returning a superset with no error. Verified live:
 * `"and"` over two clauses returned the OR result, `"AND"` returned the
 * intersection. Never widen this to accept lowercase.
 *
 * Operators verified against a live tenant: `is`, `isNot`, `contains`,
 * `notContains`, `startsWith`, `endsWith` take a string; `includes` and
 * `notIncludes` take an array. `equals` and `in` are rejected with a 500.
 *
 * Attribute and operator strings are plain `String` in the schema, so a bad
 * pair is only caught at runtime — and an unknown *value* does not error at
 * all, it silently returns zero rows.
 */
export interface RuleConditionInput {
  attribute?: string;
  operator?: string;
  value?: Json;
  joinOperator?: "AND" | "OR";
  operands?: RuleConditionInput[];
}

export interface SortInput {
  attribute?: string;
  order?: "ASC" | "DESC";
}

export interface ListInfoInput {
  page?: number;
  pageSize?: number;
  condition?: RuleConditionInput;
  sort?: SortInput[];
}

// Client types
export interface Client {
  accountId: string;
  name: string;
  stage?: string;
  status?: string;
  emailDomains?: string[];
  accountManager?: Json;
  primaryContact?: Json;
  secondaryContact?: Json;
  hqSite?: Json;
  technicianGroups?: Json;
  customFields?: Json;
}

// Ticket types
export interface Ticket {
  ticketId: string;
  /** The human-facing ticket number, e.g. "#1234". */
  displayId: string;
  subject: string;
  ticketType?: "INCIDENT" | "SERVICE_REQUEST";
  requestType?: string;
  source?: TicketSource;
  client?: Json;
  site?: Json;
  requester?: Json;
  techGroup?: Json;
  technician?: Json;
  status?: string;
  priority?: string;
  impact?: string;
  urgency?: string;
  category?: string;
  subcategory?: string;
  sla?: Json;
  createdTime?: string;
  updatedTime?: string;
  resolutionTime?: string;
  customFields?: Json;
}

export type TicketSource = "FORM" | "AGENT" | "EMAIL" | "AI" | "PHONE" | "INTEGRATION";

/** Client-portal visibility of a ticket note. */
export type NotePrivacyType = "PUBLIC" | "PRIVATE";

export interface Note {
  noteId: string;
  content: string;
  addedOn: string;
  addedBy?: Json;
  privacyType?: NotePrivacyType;
}

export interface WorklogEntry {
  itemId: string;
  qty: string;
  billDateTime: string;
  billable?: boolean;
  afterHours?: boolean;
  notes?: string;
  technician?: Json;
  workItem?: Json;
}

// Asset types
export interface Asset {
  assetId: string;
  name: string;
  hostName?: string;
  status?: string;
  platform?: string;
  platformFamily?: string;
  platformCategory?: string;
  platformVersion?: string;
  manufacturer?: string;
  model?: string;
  serialNumber?: string;
  primaryMac?: string;
  publicIp?: string;
  gateway?: string;
  domain?: string;
  loggedInUser?: string;
  sysUptime?: string;
  agentVersion?: string;
  /** A plain summary string in SuperOps, not a structured breakdown. */
  patchStatus?: string;
  warrantyExpiryDate?: string;
  purchasedDate?: string;
  lastCommunicatedTime?: string;
  lastReportedTime?: string;
  client?: Json;
  site?: Json;
  requester?: Json;
  assetClass?: Json;
  deviceCategory?: Json;
  customFields?: Json;
}

export interface AssetSoftware {
  id?: string;
  software?: Json;
  version?: string;
  installedDate?: string;
  bitVersion?: string;
  installedPath?: string;
}

/** Unlike most nested SuperOps fields, this is a real object type, not JSON. */
export interface PatchDetails {
  patchId: string;
  patchKey?: string;
  title?: string;
  publishedDate?: string;
  category?: string;
  severity?: string;
  kbNumbers?: { kbNumber?: string }[];
  restartRequired?: boolean;
}

export interface PatchData {
  patchDetail?: PatchDetails;
  approvalStatus?: string;
  installationStatus?: string;
  installationTime?: string;
  failedMessage?: string;
}

// Technician types
export interface Technician {
  userId: string;
  name: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  contactNumber?: string;
  emailSignature?: string;
  designation?: Json;
  businessFunction?: Json;
  team?: Json;
  reportingManager?: Json;
  role?: Json;
  groups?: Json;
}

export interface TechnicianGroup {
  groupId: string;
  name: string;
}

// Tool definition types
export interface ToolDefinition {
  name: string;
  description: string;
  inputSchema: {
    type: "object";
    properties: Record<string, unknown>;
    required?: string[];
  };
  /** MCP Apps (SEP-1865): advertises a ui:// resource for renderable tools. */
  _meta?: Record<string, unknown>;
}

export type Domain = "clients" | "tickets" | "assets" | "technicians" | "custom";

export interface DomainTools {
  tools: ToolDefinition[];
  handleCall: (
    name: string,
    args: Record<string, unknown>
  ) => Promise<{ content: { type: string; text: string }[]; isError?: boolean }>;
}
